# fly.toml app configuration file generated for denali-redis-sidekiq on 2025-11-30T07:43:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'denali-redis-sidekiq'
primary_region = 'iad'

[build]
  image = 'redis:7-alpine'

[processes]
  app = "redis-server --save '' --appendonly no --maxmemory 384mb --maxmemory-policy noeviction"

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 6379

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
