FROM ruby:3.4.7

RUN apt-get update && apt-get install -y --no-install-recommends curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update && apt-get install -y --no-install-recommends nodejs yarn
RUN yarn global add gulp-cli

RUN mkdir /app
WORKDIR /app
COPY . /app
RUN bundle install
RUN yarn install
RUN bundle exec rake assets:precompile
RUN bundle exec rake assets:clean
RUN mkdir tmp/pids
