# fly.toml file generated for denali on 2022-09-05T09:43:58-06:00

app = "denali"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile.production"
  [build.args]
    BUNDLER_VERSION = "2.3.13"
    NODE_VERSION = "16.15.0"
    RUBY_VERSION = "3.3.5"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bin/rails fly:server"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  web = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec sidekiq -t 25"

[[services]]
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
