class RenameAutoGeneratedAltTextAndAddTextColumn < ActiveRecord::Migration[8.0]
  def change
    # Rename existing boolean column to alt_text_needs_review
    rename_column :photos, :auto_generated_alt_text, :alt_text_needs_review

    # Add new text column for AI suggestions
    add_column :photos, :auto_generated_alt_text, :text
  end
end
