import os

MAX_AGE = 31536000

LOADER = 'tc_aws.loaders.s3_loader'
RESULT_STORAGE = 'tc_aws.result_storages.s3_storage'
STORAGE_EXPIRATION_SECONDS=2630000

SECURITY_KEY = os.environ.get('THUMBOR_SECURITY_KEY', 'MY_SECURE_KEY')
ALLOW_UNSAFE_URL = False

TC_AWS_REGION = os.environ.get('AWS_REGION', 'us-east-1')
TC_AWS_LOADER_BUCKET=False
TC_AWS_LOADER_ROOT_PATH=''
TC_AWS_ENABLE_HTTP_LOADER=True
TC_AWS_ALLOWED_BUCKETS = [b.strip() for b in os.environ.get('AWS_ALLOWED_BUCKETS', '').split(',') if b.strip()] or False

TC_AWS_RESULT_STORAGE_BUCKET = os.environ.get('AWS_RESULT_STORAGE_BUCKET', '')  # S3 bucket for result Storage
TC_AWS_RESULT_STORAGE_ROOT_PATH='' # S3 path prefix for Result storage bucket
TC_AWS_MAX_RETRY=0 # Max retries for get image from S3 Bucket. Default is 0

TC_AWS_STORE_METADATA=True # Store result with metadata (for instance content-type)
TC_AWS_RANDOMIZE_KEYS=True
