name: "Ruby on Rails CI"

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

env:
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DENALI_SECRET: ${{ secrets.DENALI_SECRET }}
  GOOGLE_APPS_DOMAIN: ${{ secrets.GOOGLE_APPS_DOMAIN }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  NODE_OPTIONS: "--openssl-legacy-provider"
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/rails_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install --frozen-lockfile

    - name: Set up database
      run: bin/rails db:schema:load

    - name: Compile assets
      run: bin/rails assets:precompile

    - name: Run tests
      run: bin/rails test
