# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
env:
  IMGIX_DOMAIN: ${{ secrets.IMGIX_DOMAIN }}
  IMGIX_API_KEY: ${{ secrets.IMGIX_API_KEY }}
  IMGIX_TOKEN: ${{ secrets.IMGIX_TOKEN }}
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DENALI_SECRET: ${{ secrets.DENALI_SECRET }}
  GOOGLE_APPS_DOMAIN: ${{ secrets.GOOGLE_APPS_DOMAIN }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      # Add or replace database setup steps here
      - name: Create database
        run: bin/rails db:create
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run migrations
        run: bin/rails db:migrate
      # Add or replace test runners here
      - name: Run tests
        run: bin/rails test
